export const launchCopy = {
  enter: "Enter the Contest",
  heroCta: "ENTER THIS MONTH'S CONTEST",
  viewRules: "READ OFFICIAL RULES",
  submit: "SUBMIT MY DOG",
  backToVerifyDog: "Back to Verify.Dog",
  verifyDogHref: "https://verify.dog",
  heroEyebrow: "WIN $500 THIS MONTH!",
  headlineLine1: "Your Dog’s Shot",
  headlineLine2: "at Fame",
  headlineStarts: "Starts",
  headlineAccent: "Here.",
  heroPrize: "WIN $500!",
  lede: "Upload the coolest 30 second video of your pup, share it with your friends, and rack up the upvotes. The dog with the most valid upvotes wins $500, and there’s a brand new contest every month.",
  snapshot: [
    {
      title: "$500 EVERY MONTH",
      body: "A new winner every month.",
      icon: "contest_trophy" as const,
      tone: "gold" as const,
    },
    {
      title: "SHOW OFF YOUR PUP",
      body: "Upload a short video of your furry friend.",
      icon: "contest_video" as const,
      tone: "blue" as const,
    },
    {
      title: "MOST UPVOTES WINS",
      body: "Share your entry and rally your friends.",
      icon: "contest_upvote" as const,
      tone: "gold" as const,
    },
  ],
  howHeading: "Enter. Share. Win.",
  howLede: "Getting started takes about a minute.",
  stages: [
    {
      step: "STEP 1",
      title: "ENTER",
      body: "Complete the contest form with your details.",
      icon: "step_enter" as const,
    },
    {
      step: "STEP 2",
      title: "UPLOAD",
      body: "Upload a 30 second vertical video of your dog.",
      icon: "step_upload" as const,
    },
    {
      step: "STEP 3",
      title: "SHARE",
      body: "Rally friends and family to upvote your entry.",
      icon: "step_share" as const,
    },
    {
      step: "STEP 4",
      title: "WIN $500",
      body: "The highest valid upvote total wins.",
      icon: "step_win" as const,
    },
  ],
  formHeading: "Enter Your Dog",
  formLede: "Your dog could be this month's $500 winner.",
  videoTitle: "VIDEO UPLOAD",
  videoHint: "Click to upload or drag and drop",
  videoSpecs: ["Vertical video", "Maximum 30 seconds", "MP4 or MOV"],
  previewLabel: "ENTRY PREVIEW PLACEHOLDER",
  formNote: "One entry per dog during each monthly contest.",
  agreement:
    "I agree to the Official Rules, Terms of Service, and Privacy Policy.",
  rulesHeading: "Contest Rules at a Glance",
  rulesBasicsHeading: "THE BASICS",
  rulesBasics: [
    "Enter once each monthly contest",
    "Upload a vertical video of your dog",
    "Maximum 30 seconds",
    "Submit original content",
    "Follow the Official Rules",
  ],
  rulesWinHeading: "HOW YOU WIN",
  rulesWin: [
    "Share your entry",
    "Invite friends to vote",
    "Collect valid upvotes",
    "Highest eligible vote total wins $500",
    "New winner every month",
  ],
  faqEyebrow: "FAQ",
  faqHeading: "Frequently Asked Questions",
  faqLede: "Questions about entering, voting, and winners.",
  faqs: [
    {
      q: "Who can enter the Doggywood contest?",
      a: "Dog owners generally. Verify.Dog sponsors Doggywood, but you do not need to be a Verify.Dog customer to enter.",
    },
    {
      q: "What kind of video can I upload?",
      a: "An original vertical video of your dog, 30 seconds or less.",
    },
    {
      q: "How do upvotes work?",
      a: "Share your entry and rally your friends to upvote. Valid upvotes count toward the monthly total.",
    },
    {
      q: "How is the winner selected?",
      a: "The dog with the most valid upvotes wins $500.",
    },
    {
      q: "Can I enter again next month?",
      a: "Yes. One entry per dog during each monthly contest.",
    },
    {
      q: "When is each winner announced?",
      a: "A new contest starts every month. Official timing is published in the Official Rules.",
    },
    {
      q: "Where can I find the full Official Rules?",
      a: "The complete Official Rules are on the Official Rules page.",
    },
  ],
  footerNote: "Sponsored by Verify.Dog",
  formDisclaimer:
    "Before your entry is accepted, your email address or mobile number will be verified by email or SMS.",
} as const;
